config/routes.rb
Rails.application.routes.draw do
    
  root to: "articles#index"
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    
    default_scope { order(created_at: :desc) }
    
    validates :title, presence: true, length: { in: 4..200 }
    validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  rescue_from ActiveRecord::RecordNotFound, with: :resource_not_found
  
  protected
  
    def resource_not_found
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  
  def index
    @articles = Article.all
  end
  
  def show
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:success] = "Article has been created"
      redirect_to articles_path
    else
      flash.now[:danger] = "Article has not been created"
      render 'new'
    end
  end
  
  def update
    if @article.update_attributes(article_params)
      flash[:success] = "Article has been updated"
      redirect_to @article
    else
      flash.now[:danger] = "Article has not been updated"
      render :edit
    end
  end
  
  def edit
  end
  
  def destroy
    @article.destroy
    flash[:success] = "Article has been deleted"
    redirect_to root_path
  end
  
  protected
  
    def resource_not_found
      message = "Article you are looking for could not be found"
      flash[:warning] = message
      redirect_to root_path
    end
  
  private
  
    def set_article
      @article = Article.find(params[:id])
    end
  
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article, html: {class: "form-horizontal", role: "form"} do |f| %>
    <%= render 'shared/form_errors', object: f.object %>
    <div class="form-group">
        <div class="control-label col-md-1">
            <%= f.label :title %>
        </div>
        <div class="col-md-11">
            <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
    </div>
    <div class="form-group">
        <div class="control-label col-md-1">
            <%= f.label :body %>
        </div>
        <div class="col-md-11">
            <%= f.text_area :body, rows: 10, class: "form-control", placeholder: "Body of article" %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-1 col-md-11">
            <%= f.submit class: "btn btn-primary btn-lg pull-right" %>
        </div>
    </div>
<% end %>

app/views/articles/edit.html.erb
<div class="container">
    <h3 class="text-center">Editing Article</h3>
    
    <div class="row">
        <div class="col-md-12">
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/articles/index.html.erb
<%= link_to "New Article", new_article_path, class: "btn btn-default btn-ld", id: "new-article-btn" %>

<% if @articles.empty? %>
    <h1 id="no-articles">No Articles to Display</h1>
<% else %>
    <% @articles.each do |article| %>
        <div class="well well-lg">
            <div class="article-title">
                <%= link_to article.title, article %>
            </div>
            <div class="article-body">
                <%= truncate(article.body, length: 500) %>
            </div>
        </div>
    <% end %>
<% end %>

app/views/articles/new.html.erb
<div class="container">
    <h3 class="text-center">Adding New Article</h3>
    
    <div class="row">
        <div class="col-md-12">
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/articles/show.html.erb
<div class="container">
    <article class="article-detail">
        <h1 class="article-detail-title"><%= @article.title %></h1>
        <div class="glyphicon glyphicon-calender" id="article-date">
            <%= @article.created_at.strftime("%b %d %Y") %>
        </div>
        <div class="article-body">
            <%= @article.body %>
        </div>
        <div class="edit-delete">
            <%= link_to "Edit Article", edit_article_path(@article), class: "btn btn-primary btn-large btn-space" %>
            <%= link_to "Delete Article", article_path(@article), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }, class: "btn btn-primary btn-large btn-space" %>
        </div>
    </article>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "text-center alert alert-#{message_type}", id: "flash") %>
<% end %>

app/views/layouts/_navbar.html.erb
<header role="banner">
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-fluid"> 
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> 
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "Blog App", root_path, class: "navbar-brand" %> 
            </div>
            <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><%= link_to "Authors", "#" %></li>
                </ul> 
            </div>
        </div> 
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_form_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>:
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    
  </div>
<% end %>